import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { BookOpen, Brain, Timer, Search, ArrowRight, Sparkles } from "lucide-react";

export default function Index() {
  const { user } = useAuth();

  const features = [
    { icon: Timer, title: "Study Tracker", desc: "Track sessions with a built-in timer and view your history." },
    { icon: Brain, title: "AI Study Advisor", desc: "Get personalized study plans generated by AI." },
    { icon: Search, title: "Resource Finder", desc: "Discover curated videos, articles, and courses." },
    { icon: Sparkles, title: "Smart Analytics", desc: "Visualize your progress with charts and streaks." },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Navbar */}
      <nav className="w-full py-5 px-8 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
            <BookOpen className="w-4 h-4 text-primary-foreground" />
          </div>
          <span className="text-lg font-bold text-foreground">StudyMate AI</span>
        </div>
        <div>
          {user ? (
            <Link to="/dashboard">
              <Button variant="hero" size="sm">Go to Dashboard</Button>
            </Link>
          ) : (
            <Link to="/login">
              <Button variant="heroSecondary" size="sm">Sign Up</Button>
            </Link>
          )}
        </div>
      </nav>
      <div className="mt-[3px] w-full h-px bg-gradient-to-r from-transparent via-foreground/20 to-transparent" />

      {/* Hero */}
      <section className="relative overflow-hidden pt-20 pb-24 px-4">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent pointer-events-none" />
        <div className="relative max-w-3xl mx-auto text-center space-y-6">
          <h1
            className="text-6xl md:text-8xl font-bold tracking-tight bg-clip-text text-transparent"
            style={{ backgroundImage: "linear-gradient(223deg, hsl(40 10% 96%) 0%, hsl(262 83% 58%) 104.15%)" }}
          >
            StudyMate
          </h1>
          <p className="text-hero-sub text-lg leading-8 max-w-md mx-auto opacity-80">
            The most powerful AI study companion.<br />Master any subject, ace every exam.
          </p>
          <div className="flex items-center justify-center gap-4 mt-8">
            <Link to={user ? "/dashboard" : "/login"}>
              <Button variant="hero" className="gap-2 px-8 py-6 text-base">
                <Sparkles className="w-4 h-4" /> Get Started Free <ArrowRight className="w-4 h-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-5xl mx-auto px-4 pb-24">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {features.map((f) => (
            <div key={f.title} className="bg-card border border-border rounded-xl p-6 space-y-3 hover:border-primary/30 transition-colors">
              <f.icon className="w-8 h-8 text-primary" />
              <h3 className="text-lg font-semibold text-foreground">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Logo Marquee */}
      <section className="relative w-full overflow-hidden py-16 border-t border-border">
        <div className="max-w-5xl mx-auto px-4 flex items-center gap-12">
          <p className="text-foreground/50 text-sm whitespace-nowrap shrink-0">
            Trusted by students<br />across the globe
          </p>
          <div className="overflow-hidden flex-1">
            <div className="flex animate-marquee gap-16">
              {["Oxford", "Stanford", "MIT", "Harvard", "Cambridge", "Yale", "Oxford", "Stanford", "MIT", "Harvard", "Cambridge", "Yale"].map((name, i) => (
                <div key={i} className="flex items-center gap-2 shrink-0">
                  <div className="liquid-glass w-6 h-6 rounded-lg flex items-center justify-center text-xs font-bold text-foreground">{name[0]}</div>
                  <span className="text-base font-semibold text-foreground whitespace-nowrap">{name}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
